// <auto-generated />
using System;
using BancoDeDadosKasaleveSistema.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BancoDeDadosKasaleveSistema.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BancoDeDadosKasaleveSistema.Models.AluminioCor", b =>
                {
                    b.Property<int>("AluminioCorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AluminioCorId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AluminioCorId"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CodigoAluminioCor");

                    b.Property<string>("CorAluminioCor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CorAluminioCor");

                    b.Property<string>("HexCor")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasColumnName("hexCor");

                    b.Property<string>("SKUAluminioCor")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("SKUAluminioCor");

                    b.HasKey("AluminioCorId");

                    b.ToTable("AluminioCor");
                });

            modelBuilder.Entity("BancoDeDadosKasaleveSistema.Models.Cargo", b =>
                {
                    b.Property<int>("CargoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CargoId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CargoId"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("ativo");

                    b.Property<string>("CargoDescricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CargoDescricao");

                    b.Property<string>("CargoNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CargoNome");

                    b.HasKey("CargoId");

                    b.ToTable("Cargo");
                });

            modelBuilder.Entity("BancoDeDadosKasaleveSistema.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CategoriaId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("ativo");

                    b.Property<string>("CategoriaDescricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CategoriaDescricao");

                    b.Property<string>("CategoriaNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CategoriaNome");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("BancoDeDadosKasaleveSistema.Models.Checklist", b =>
                {
                    b.Property<int>("ChecklistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ChecklistId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChecklistId"));

                    b.Property<string>("Alteracao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("alteracao");

                    b.Property<string>("Bairro")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("cep");

                    b.Property<string>("ChecklistEnderecoEntrega")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ChecklistenderecoEntrega");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("cidade");

                    b.Property<bool>("ConferirProduto")
                        .HasColumnType("bit")
                        .HasColumnName("conferirProduto");

                    b.Property<string>("Cores")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("cores");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataConclusao");

                    b.Property<string>("Frete")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("frete");

                    b.Property<bool>("Imprimir")
                        .HasColumnType("bit")
                        .HasColumnName("imprimir");

                    b.Property<bool>("MesaComFuro")
                        .HasColumnType("bit")
                        .HasColumnName("mesaComFuro");

                    b.Property<string>("Nota")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("nota");

                    b.Property<int?>("OrcamentoId")
                        .HasColumnType("int")
                        .HasColumnName("OrcamentoId");

                    b.Property<DateTime?>("Prazo")
                        .HasColumnType("datetime2")
                        .HasColumnName("prazo");

                    b.Property<DateTime?>("PrevisaoEntrega")
                        .HasColumnType("datetime2")
                        .HasColumnName("previsaoEntrega");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuarioId");

                    b.HasKey("ChecklistId");

                    b.HasIndex("OrcamentoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Checklist");
                });

            modelBuilder.Entity("BancoDeDadosKasaleveSistema.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ClienteId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<string>("Cep")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("cidade");

                    b.Property<string>("CpfCnpj")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("cpfCnpj");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataCadastro");

                    b.Property<string>("Endereco")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("endereco");

                    b.Property<string>("Estado")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("estado");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nome");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("status");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("telefone");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuarioId");

                    b.HasKey("ClienteId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("BancoDeDadosKasaleveSistema.Models.CordaCor", b =>
                {
                    b.Property<int>("CordaCorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CordaCorId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CordaCorId"));

                    b.Property<string>("HexCor")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasColumnName("hexCor");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Sku")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("sku");

                    b.HasKey("CordaCorId");

                    b.ToTable("CordaCor");
                });

            modelBuilder.Entity("BancoDeDadosKasaleveSistema.Models.Estoque", b =>
                {
                    b.Property<int>("EstoqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EstoqueId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstoqueId"));

                    b.Property<DateTime>("DataModificacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataModificacao");

                    b.Property<int>("EstoqueMinimo")
                        .HasColumnType("int")
                        .HasColumnName("estoqueMinimo");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("localizacao");

                    b.Property<int>("ProdutoVariacaoId")
                        .HasColumnType("int")
                        .HasColumnName("produtoVariacaoId");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int")
                        .HasColumnName("quantidade");

                    b.HasKey("EstoqueId");

                    b.HasIndex("ProdutoVariacaoId", "Localizacao")
                        .IsUnique();

                    b.ToTable("Estoque");
                });

            modelBuilder.Entity("BancoDeDadosKasaleveSistema.Models.FibraCor", b =>
                {
                    b.Property<int>("FibraCorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FibraCorId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FibraCorId"));

                    b.Property<string>("HexCor")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasColumnName("hexCor");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Sku")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sku");

                    b.HasKey("FibraCorId");

                    b.ToTable("FibraCor");
                });

            modelBuilder.Entity("BancoDeDadosKasaleveSistema.Models.Historico", b =>
                {
                    b.Property<int>("HistoricoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HistoricoId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoricoId"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("acao");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataHora");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("descricao");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("entidade");

                    b.Property<int>("EntidadeId")
                        .HasColumnType("int")
                        .HasColumnName("entidadeId");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuarioId");

                    b.HasKey("HistoricoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Historico");
                });

            modelBuilder.Entity("BancoDeDadosKasaleveSistema.Models.MovimentacaoEstoque", b =>
                {
                    b.Property<int>("MovimentacaoEstoqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MovimentacaoEstoqueId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovimentacaoEstoqueId"));

                    b.Property<DateTime>("DataMovimentacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataMovimentacao");

                    b.Property<string>("DescricaoVariacao")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("descricaoVariacao");

                    b.Property<int>("EstoqueId")
                        .HasColumnType("int")
                        .HasColumnName("estoqueId");

                    b.Property<string>("LocalizacaoRegistro")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("localizacaoRegistro");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("motivo");

                    b.Property<string>("Obs")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("obs");

                    b.Property<int?>("OrcamentoId")
                        .HasColumnType("int")
                        .HasColumnName("orcamentoId");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int")
                        .HasColumnName("quantidade");

                    b.Property<int>("SaldoAnterior")
                        .HasColumnType("int")
                        .HasColumnName("saldoAnterior");

                    b.Property<int>("SaldoPosterior")
                        .HasColumnType("int")
                        .HasColumnName("saldoPosterior");

                    b.Property<int>("TipoMovimentacaoId")
                        .HasColumnType("int")
                        .HasColumnName("tipoMovimentacaoId");

                    b.Property<Guid?>("TransferenciaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("transferenciaId");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuarioId");

                    b.HasKey("MovimentacaoEstoqueId");

                    b.HasIndex("OrcamentoId");

                    b.HasIndex("TipoMovimentacaoId");

                    b.HasIndex("TransferenciaId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("EstoqueId", "DataMovimentacao");

                    b.ToTable("MovimentacaoEstoque");
                });

            modelBuilder.Entity("BancoDeDadosKasaleveSistema.Models.Orcamento", b =>
                {
                    b.Property<int>("OrcamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrcamentoId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrcamentoId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("clienteId");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataAlteracao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataCriacao");

                    b.Property<decimal>("Desconto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("desconto");

                    b.Property<decimal>("Frete")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("frete");

                    b.Property<string>("Obs")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("obs");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<decimal>("SubTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("subTotal");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuarioId");

                    b.Property<DateTime?>("Validade")
                        .HasColumnType("datetime2")
                        .HasColumnName("validade");

                    b.HasKey("OrcamentoId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Orcamento");
                });

            modelBuilder.Entity("BancoDeDadosKasaleveSistema.Models.OrcamentoItem", b =>
                {
                    b.Property<string>("OrcamentoItemId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("OrcamentoItemId");

                    b.Property<decimal>("Desconto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("desconto");

                    b.Property<string>("NomeProdutoSnapshot")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nomeProdutoSnapshot");

                    b.Property<string>("Obs")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("obs");

                    b.Property<int?>("OrcamentoId")
                        .HasColumnType("int")
                        .HasColumnName("OrcamentoId");

                    b.Property<int>("ProdutoVariacaoId")
                        .HasColumnType("int")
                        .HasColumnName("produtoVariacaoId");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int")
                        .HasColumnName("quantidade");

                    b.Property<decimal>("ValorExtra")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valorExtra");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valorTotal");

                    b.Property<decimal>("ValorUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valorUnitario");

                    b.HasKey("OrcamentoItemId");

                    b.HasIndex("OrcamentoId");

                    b.HasIndex("ProdutoVariacaoId");

                    b.ToTable("OrcamentoItem");
                });

            modelBuilder.Entity("BancoDeDadosKasaleveSistema.Models.Produto", b =>
                {
                    b.Property<int>("ProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProdutoId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProdutoId"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("ativo");

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("int")
                        .HasColumnName("categoriaId");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataCadastro");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descricao");

                    b.Property<int>("EstoqueMinimo")
                        .HasColumnType("int")
                        .HasColumnName("estoqueMinimo");

                    b.Property<string>("Img")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("img");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nome");

                    b.Property<string>("Sku")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sku");

                    b.Property<decimal>("ValorFinal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valorFinal");

                    b.Property<decimal>("ValorLogista")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valorLogista");

                    b.HasKey("ProdutoId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("BancoDeDadosKasaleveSistema.Models.ProdutoVariacao", b =>
                {
                    b.Property<int>("ProdutoVariacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProdutoVariacaoId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProdutoVariacaoId"));

                    b.Property<int?>("AluminioCorId")
                        .HasColumnType("int")
                        .HasColumnName("aluminioCorId");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("ativo");

                    b.Property<int?>("CordaCorId")
                        .HasColumnType("int")
                        .HasColumnName("cordaCorId");

                    b.Property<int?>("FibraCorId")
                        .HasColumnType("int")
                        .HasColumnName("fibraCorId");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int")
                        .HasColumnName("produtoId");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sku");

                    b.Property<int?>("TecidoId")
                        .HasColumnType("int")
                        .HasColumnName("tecidoId");

                    b.HasKey("ProdutoVariacaoId");

                    b.HasIndex("AluminioCorId");

                    b.HasIndex("CordaCorId");

                    b.HasIndex("FibraCorId");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("TecidoId");

                    b.ToTable("ProdutoVariacao");
                });

            modelBuilder.Entity("BancoDeDadosKasaleveSistema.Models.Tecido", b =>
                {
                    b.Property<int>("TecidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TecidoId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TecidoId"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Sku")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sku");

                    b.HasKey("TecidoId");

                    b.ToTable("Tecido");
                });

            modelBuilder.Entity("BancoDeDadosKasaleveSistema.Models.TipoMovimentacao", b =>
                {
                    b.Property<int>("TipoMovimentacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TipoMovimentacaoId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoMovimentacaoId"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("descricao");

                    b.Property<bool>("Entrada")
                        .HasColumnType("bit")
                        .HasColumnName("entrada");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nome");

                    b.HasKey("TipoMovimentacaoId");

                    b.ToTable("TipoMovimentacao");
                });

            modelBuilder.Entity("BancoDeDadosKasaleveSistema.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UsuarioId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<int>("CargoId")
                        .HasColumnType("int")
                        .HasColumnName("cargoId");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataCadastro");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nome");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("senhaHash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("status");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("telefone");

                    b.HasKey("UsuarioId");

                    b.HasIndex("CargoId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("BancoDeDadosKasaleveSistema.Models.Checklist", b =>
                {
                    b.HasOne("BancoDeDadosKasaleveSistema.Models.Orcamento", "Orcamento")
                        .WithMany("Checklists")
                        .HasForeignKey("OrcamentoId");

                    b.HasOne("BancoDeDadosKasaleveSistema.Models.Usuario", "Usuario")
                        .WithMany("Checklists")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Orcamento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BancoDeDadosKasaleveSistema.Models.Cliente", b =>
                {
                    b.HasOne("BancoDeDadosKasaleveSistema.Models.Usuario", "Usuario")
                        .WithMany("ClientesResponsavel")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BancoDeDadosKasaleveSistema.Models.Estoque", b =>
                {
                    b.HasOne("BancoDeDadosKasaleveSistema.Models.ProdutoVariacao", "ProdutoVariacao")
                        .WithMany("Estoques")
                        .HasForeignKey("ProdutoVariacaoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProdutoVariacao");
                });

            modelBuilder.Entity("BancoDeDadosKasaleveSistema.Models.Historico", b =>
                {
                    b.HasOne("BancoDeDadosKasaleveSistema.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BancoDeDadosKasaleveSistema.Models.MovimentacaoEstoque", b =>
                {
                    b.HasOne("BancoDeDadosKasaleveSistema.Models.Estoque", "Estoque")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("EstoqueId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BancoDeDadosKasaleveSistema.Models.Orcamento", "Orcamento")
                        .WithMany()
                        .HasForeignKey("OrcamentoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BancoDeDadosKasaleveSistema.Models.TipoMovimentacao", "TipoMovimentacao")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("TipoMovimentacaoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BancoDeDadosKasaleveSistema.Models.Usuario", "Usuario")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Estoque");

                    b.Navigation("Orcamento");

                    b.Navigation("TipoMovimentacao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BancoDeDadosKasaleveSistema.Models.Orcamento", b =>
                {
                    b.HasOne("BancoDeDadosKasaleveSistema.Models.Cliente", "Cliente")
                        .WithMany("Orcamentos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BancoDeDadosKasaleveSistema.Models.Usuario", "Usuario")
                        .WithMany("Orcamentos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BancoDeDadosKasaleveSistema.Models.OrcamentoItem", b =>
                {
                    b.HasOne("BancoDeDadosKasaleveSistema.Models.Orcamento", "Orcamento")
                        .WithMany("Itens")
                        .HasForeignKey("OrcamentoId");

                    b.HasOne("BancoDeDadosKasaleveSistema.Models.ProdutoVariacao", "ProdutoVariacao")
                        .WithMany("OrcamentoItens")
                        .HasForeignKey("ProdutoVariacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orcamento");

                    b.Navigation("ProdutoVariacao");
                });

            modelBuilder.Entity("BancoDeDadosKasaleveSistema.Models.Produto", b =>
                {
                    b.HasOne("BancoDeDadosKasaleveSistema.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("BancoDeDadosKasaleveSistema.Models.ProdutoVariacao", b =>
                {
                    b.HasOne("BancoDeDadosKasaleveSistema.Models.AluminioCor", "AluminioCor")
                        .WithMany()
                        .HasForeignKey("AluminioCorId");

                    b.HasOne("BancoDeDadosKasaleveSistema.Models.CordaCor", "CordaCor")
                        .WithMany("Variacoes")
                        .HasForeignKey("CordaCorId");

                    b.HasOne("BancoDeDadosKasaleveSistema.Models.FibraCor", "FibraCor")
                        .WithMany("Variacoes")
                        .HasForeignKey("FibraCorId");

                    b.HasOne("BancoDeDadosKasaleveSistema.Models.Produto", "Produto")
                        .WithMany("Variacoes")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BancoDeDadosKasaleveSistema.Models.Tecido", "Tecido")
                        .WithMany("Variacoes")
                        .HasForeignKey("TecidoId");

                    b.Navigation("AluminioCor");

                    b.Navigation("CordaCor");

                    b.Navigation("FibraCor");

                    b.Navigation("Produto");

                    b.Navigation("Tecido");
                });

            modelBuilder.Entity("BancoDeDadosKasaleveSistema.Models.Usuario", b =>
                {
                    b.HasOne("BancoDeDadosKasaleveSistema.Models.Cargo", "Cargo")
                        .WithMany()
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cargo");
                });

            modelBuilder.Entity("BancoDeDadosKasaleveSistema.Models.Cliente", b =>
                {
                    b.Navigation("Orcamentos");
                });

            modelBuilder.Entity("BancoDeDadosKasaleveSistema.Models.CordaCor", b =>
                {
                    b.Navigation("Variacoes");
                });

            modelBuilder.Entity("BancoDeDadosKasaleveSistema.Models.Estoque", b =>
                {
                    b.Navigation("Movimentacoes");
                });

            modelBuilder.Entity("BancoDeDadosKasaleveSistema.Models.FibraCor", b =>
                {
                    b.Navigation("Variacoes");
                });

            modelBuilder.Entity("BancoDeDadosKasaleveSistema.Models.Orcamento", b =>
                {
                    b.Navigation("Checklists");

                    b.Navigation("Itens");
                });

            modelBuilder.Entity("BancoDeDadosKasaleveSistema.Models.Produto", b =>
                {
                    b.Navigation("Variacoes");
                });

            modelBuilder.Entity("BancoDeDadosKasaleveSistema.Models.ProdutoVariacao", b =>
                {
                    b.Navigation("Estoques");

                    b.Navigation("OrcamentoItens");
                });

            modelBuilder.Entity("BancoDeDadosKasaleveSistema.Models.Tecido", b =>
                {
                    b.Navigation("Variacoes");
                });

            modelBuilder.Entity("BancoDeDadosKasaleveSistema.Models.TipoMovimentacao", b =>
                {
                    b.Navigation("Movimentacoes");
                });

            modelBuilder.Entity("BancoDeDadosKasaleveSistema.Models.Usuario", b =>
                {
                    b.Navigation("Checklists");

                    b.Navigation("ClientesResponsavel");

                    b.Navigation("Movimentacoes");

                    b.Navigation("Orcamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
